// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqjPV_dLcXjxsjEVGZgDzFNXK1KMkMNUA',
    appId: '1:6345327773:android:5ee6644dc2a22133c44074',
    messagingSenderId: '6345327773',
    projectId: 'exploreworld-6d854',
    storageBucket: 'exploreworld-6d854.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYoanEtJHSYiePsukG5Ywcgue2anu7AFk',
    appId: '1:6345327773:ios:0dc8b034ba50fac3c44074',
    messagingSenderId: '6345327773',
    projectId: 'exploreworld-6d854',
    storageBucket: 'exploreworld-6d854.appspot.com',
    iosBundleId: 'com.example.exploreWorld',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYoanEtJHSYiePsukG5Ywcgue2anu7AFk',
    appId: '1:6345327773:ios:0dc8b034ba50fac3c44074',
    messagingSenderId: '6345327773',
    projectId: 'exploreworld-6d854',
    storageBucket: 'exploreworld-6d854.appspot.com',
    iosBundleId: 'com.example.exploreWorld',
  );
}
